/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-04-08 07:16:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Chat - Marketing Team - ChatWave</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://unpkg.com/lucide@latest/dist/umd/lucide.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        .message-container {\r\n");
      out.write("            max-height: calc(100vh - 200px);\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-50 h-screen flex flex-col\">\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"bg-white shadow-sm\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"flex justify-between h-16\">\r\n");
      out.write("                <div class=\"flex\">\r\n");
      out.write("                    <div class=\"flex-shrink-0 flex items-center\">\r\n");
      out.write("                        <h1 class=\"text-2xl font-bold text-purple-600\">ChatWave</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex items-center\">\r\n");
      out.write("                    <button type=\"button\" class=\"p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\">\r\n");
      out.write("                        <span class=\"sr-only\">View notifications</span>\r\n");
      out.write("                        <svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"ml-3 relative\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <button type=\"button\" class=\"max-w-xs bg-white flex items-center text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\" id=\"user-menu-button\" aria-expanded=\"false\" aria-haspopup=\"true\">\r\n");
      out.write("                                <span class=\"sr-only\">Open user menu</span>\r\n");
      out.write("                                <img class=\"h-8 w-8 rounded-full\" src=\"https://randomuser.me/api/portraits/men/32.jpg\" alt=\"\">\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"flex-1 flex overflow-hidden\">\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <div class=\"w-64 bg-white border-r border-gray-200 flex-shrink-0\">\r\n");
      out.write("            <div class=\"h-full flex flex-col\">\r\n");
      out.write("                <!-- Search -->\r\n");
      out.write("                <div class=\"p-4 border-b border-gray-200\">\r\n");
      out.write("                    <div class=\"relative rounded-md shadow-sm\">\r\n");
      out.write("                        <div class=\"absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none\">\r\n");
      out.write("                            <svg class=\"h-5 w-5 text-gray-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                <path fill-rule=\"evenodd\" d=\"M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z\" clip-rule=\"evenodd\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"text\" name=\"search\" id=\"search\" class=\"focus:ring-purple-500 focus:border-purple-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md\" placeholder=\"Search\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Chats -->\r\n");
      out.write("                <div class=\"flex-1 overflow-y-auto\">\r\n");
      out.write("                    <div class=\"p-4\">\r\n");
      out.write("                        <h2 class=\"text-xs font-semibold text-gray-500 uppercase tracking-wider\">Direct Messages</h2>\r\n");
      out.write("                        <ul class=\"mt-2 space-y-1\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"flex items-center px-3 py-2 text-sm font-medium rounded-md text-gray-700 hover:text-gray-900 hover:bg-gray-50\">\r\n");
      out.write("                                    <img class=\"h-8 w-8 rounded-full mr-2\" src=\"https://randomuser.me/api/portraits/women/32.jpg\" alt=\"\">\r\n");
      out.write("                                    <span>Sarah Johnson</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"flex items-center px-3 py-2 text-sm font-medium rounded-md text-gray-700 hover:text-gray-900 hover:bg-gray-50\">\r\n");
      out.write("                                    <img class=\"h-8 w-8 rounded-full mr-2\" src=\"https://randomuser.me/api/portraits/men/46.jpg\" alt=\"\">\r\n");
      out.write("                                    <span>Michael Chen</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"flex items-center px-3 py-2 text-sm font-medium rounded-md text-gray-700 hover:text-gray-900 hover:bg-gray-50\">\r\n");
      out.write("                                    <img class=\"h-8 w-8 rounded-full mr-2\" src=\"https://randomuser.me/api/portraits/women/65.jpg\" alt=\"\">\r\n");
      out.write("                                    <span>Emily Rodriguez</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"p-4\">\r\n");
      out.write("                        <h2 class=\"text-xs font-semibold text-gray-500 uppercase tracking-wider\">Group Chats</h2>\r\n");
      out.write("                        <ul class=\"mt-2 space-y-1\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"flex items-center px-3 py-2 text-sm font-medium rounded-md text-gray-700 bg-gray-100\">\r\n");
      out.write("                                    <span class=\"w-8 h-8 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center mr-2\">\r\n");
      out.write("                                        <svg class=\"h-5 w-5\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z\" />\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span>Marketing Team</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"flex items-center px-3 py-2 text-sm font-medium rounded-md text-gray-700 hover:text-gray-900 hover:bg-gray-50\">\r\n");
      out.write("                                    <span class=\"w-8 h-8 rounded-full bg-green-100 text-green-700 flex items-center justify-center mr-2\">\r\n");
      out.write("                                        <svg class=\"h-5 w-5\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10\" />\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span>Project Alpha</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\" class=\"flex items-center px-3 py-2 text-sm font-medium rounded-md text-gray-700 hover:text-gray-900 hover:bg-gray-50\">\r\n");
      out.write("                                    <span class=\"w-8 h-8 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center mr-2\">\r\n");
      out.write("                                        <svg class=\"h-5 w-5\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 6v6m0 0v6m0-6h6m-6 0H6\" />\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span>General</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Create New Chat -->\r\n");
      out.write("                <div class=\"p-4 border-t border-gray-200\">\r\n");
      out.write("                    <button type=\"button\" class=\"w-full flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\">\r\n");
      out.write("                        <svg class=\"h-5 w-5 mr-2\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 6v6m0 0v6m0-6h6m-6 0H6\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                        New Chat\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Chat Area -->\r\n");
      out.write("        <div class=\"flex-1 flex flex-col bg-white\">\r\n");
      out.write("            <!-- Chat Header -->\r\n");
      out.write("            <div class=\"border-b border-gray-200 px-6 py-4 flex items-center\">\r\n");
      out.write("                <div class=\"flex-shrink-0\">\r\n");
      out.write("                    <span class=\"w-10 h-10 rounded-full bg-purple-100 text-purple-700 flex items-center justify-center\">\r\n");
      out.write("                        <svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"ml-3\">\r\n");
      out.write("                    <h2 class=\"text-lg font-medium text-gray-900\">Marketing Team</h2>\r\n");
      out.write("                    <p class=\"text-sm text-gray-500\">5 members â¢ 2 online</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"ml-auto flex items-center\">\r\n");
      out.write("                    <button type=\"button\" class=\"inline-flex items-center p-2 border border-transparent rounded-full shadow-sm text-gray-400 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\">\r\n");
      out.write("                        <svg class=\"h-5 w-5\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button type=\"button\" class=\"ml-2 inline-flex items-center p-2 border border-transparent rounded-full shadow-sm text-gray-400 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\">\r\n");
      out.write("                        <svg class=\"h-5 w-5\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Messages -->\r\n");
      out.write("            <div class=\"flex-1 p-6 overflow-y-auto message-container\">\r\n");
      out.write("                <div class=\"space-y-6\">\r\n");
      out.write("                    <!-- Day Divider -->\r\n");
      out.write("                    <div class=\"flex items-center\">\r\n");
      out.write("                        <div class=\"flex-grow border-t border-gray-200\"></div>\r\n");
      out.write("                        <span class=\"flex-shrink mx-4 text-sm text-gray-400\">Today</span>\r\n");
      out.write("                        <div class=\"flex-grow border-t border-gray-200\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Message: Other Person -->\r\n");
      out.write("                    <div class=\"flex items-start\">\r\n");
      out.write("                        <img class=\"h-10 w-10 rounded-full mr-4\" src=\"https://randomuser.me/api/portraits/women/32.jpg\" alt=\"\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"flex items-center\">\r\n");
      out.write("                                <h3 class=\"text-sm font-medium text-gray-900\">Sarah Johnson</h3>\r\n");
      out.write("                                <span class=\"ml-2 text-xs text-gray-500\">10:32 AM</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mt-1 bg-gray-100 rounded-lg p-3 text-sm text-gray-700\">\r\n");
      out.write("                                <p>Hey team! I've just finished the marketing report for Q2. I'll be sharing it with everyone shortly.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Message: Other Person with File -->\r\n");
      out.write("                    <div class=\"flex items-start\">\r\n");
      out.write("                        <img class=\"h-10 w-10 rounded-full mr-4\" src=\"https://randomuser.me/api/portraits/women/32.jpg\" alt=\"\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"flex items-center\">\r\n");
      out.write("                                <h3 class=\"text-sm font-medium text-gray-900\">Sarah Johnson</h3>\r\n");
      out.write("                                <span class=\"ml-2 text-xs text-gray-500\">10:35 AM</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mt-1 bg-gray-100 rounded-lg p-3 text-sm text-gray-700\">\r\n");
      out.write("                                <p>Here's the file:</p>\r\n");
      out.write("                                <div class=\"mt-2 flex items-center p-2 border border-gray-200 rounded-md bg-white\">\r\n");
      out.write("                                    <svg class=\"h-8 w-8 text-red-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                        <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <div class=\"ml-2\">\r\n");
      out.write("                                        <p class=\"text-sm font-medium text-gray-900\">Q2_Marketing_Report.pdf</p>\r\n");
      out.write("                                        <p class=\"text-xs text-gray-500\">2.4 MB</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button type=\"button\" class=\"ml-auto p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\">\r\n");
      out.write("                                        <svg class=\"h-5 w-5\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4\" />\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Message: Other Person -->\r\n");
      out.write("                    <div class=\"flex items-start\">\r\n");
      out.write("                        <img class=\"h-10 w-10 rounded-full mr-4\" src=\"https://randomuser.me/api/portraits/men/46.jpg\" alt=\"\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"flex items-center\">\r\n");
      out.write("                                <h3 class=\"text-sm font-medium text-gray-900\">Michael Chen</h3>\r\n");
      out.write("                                <span class=\"ml-2 text-xs text-gray-500\">10:40 AM</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mt-1 bg-gray-100 rounded-lg p-3 text-sm text-gray-700\">\r\n");
      out.write("                                <p>Thanks Sarah! Looking forward to reviewing it. Do we need to prepare anything for the meeting with the client tomorrow?</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Message: Current User -->\r\n");
      out.write("                    <div class=\"flex items-start justify-end\">\r\n");
      out.write("                        <div class=\"max-w-lg\">\r\n");
      out.write("                            <div class=\"flex items-center justify-end\">\r\n");
      out.write("                                <span class=\"text-xs text-gray-500\">10:42 AM</span>\r\n");
      out.write("                                <h3 class=\"ml-2 text-sm font-medium text-gray-900\">You</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mt-1 bg-purple-600 rounded-lg p-3 text-sm text-white\">\r\n");
      out.write("                                <p>I've already prepared the presentation slides. I'll share them in a moment.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <img class=\"h-10 w-10 rounded-full ml-4\" src=\"https://randomuser.me/api/portraits/men/32.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Message: Current User with Image -->\r\n");
      out.write("                    <div class=\"flex items-start justify-end\">\r\n");
      out.write("                        <div class=\"max-w-lg\">\r\n");
      out.write("                            <div class=\"flex items-center justify-end\">\r\n");
      out.write("                                <span class=\"text-xs text-gray-500\">10:45 AM</span>\r\n");
      out.write("                                <h3 class=\"ml-2 text-sm font-medium text-gray-900\">You</h3>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mt-1 bg-purple-600 rounded-lg p-3 text-sm text-white\">\r\n");
      out.write("                                <p>Here's a preview of the main slide:</p>\r\n");
      out.write("                                <div class=\"mt-2 rounded-md overflow-hidden\">\r\n");
      out.write("                                    <img src=\"https://images.unsplash.com/photo-1557804506-669a67965ba0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1567&q=80\" alt=\"Presentation slide\" class=\"w-full h-auto\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <img class=\"h-10 w-10 rounded-full ml-4\" src=\"https://randomuser.me/api/portraits/men/32.jpg\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Message: Other Person -->\r\n");
      out.write("                    <div class=\"flex items-start\">\r\n");
      out.write("                        <img class=\"h-10 w-10 rounded-full mr-4\" src=\"https://randomuser.me/api/portraits/women/65.jpg\" alt=\"\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div class=\"flex items-center\">\r\n");
      out.write("                                <h3 class=\"text-sm font-medium text-gray-900\">Emily Rodriguez</h3>\r\n");
      out.write("                                <span class=\"ml-2 text-xs text-gray-500\">10:50 AM</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mt-1 bg-gray-100 rounded-lg p-3 text-sm text-gray-700\">\r\n");
      out.write("                                <p>Looks great! I think we're well prepared for tomorrow. Let's have a quick call at 4 PM to go through everything one more time. Does that work for everyone?</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Message Input -->\r\n");
      out.write("            <div class=\"border-t border-gray-200 p-4 bg-white\">\r\n");
      out.write("                <form class=\"flex items-center\">\r\n");
      out.write("                    <button type=\"button\" class=\"p-2 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\">\r\n");
      out.write("                        <svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <input type=\"text\" placeholder=\"Type your message...\" class=\"flex-1 border-0 focus:ring-0 focus:outline-none px-4 py-2 text-sm text-gray-700\">\r\n");
      out.write("                    <div class=\"flex\">\r\n");
      out.write("                        <button type=\"button\" class=\"p-2 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\">\r\n");
      out.write("                            <svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"submit\" class=\"ml-2 inline-flex items-center justify-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\">\r\n");
      out.write("                            <svg class=\"h-5 w-5\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 19l9 2-9-18-9 18 9-2zm0 0v-8\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
