/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-04-08 07:16:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>ChatWave - Modern Team Communication</title>\r\n");
      out.write("    <script src=\"https://cdn.tailwindcss.com\"></script>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://unpkg.com/lucide@latest/dist/umd/lucide.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Inter', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-gray-50 min-h-screen\">\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"bg-white shadow-sm fixed w-full z-10\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"flex justify-between h-16\">\r\n");
      out.write("                <div class=\"flex\">\r\n");
      out.write("                    <div class=\"flex-shrink-0 flex items-center\">\r\n");
      out.write("                        <h1 class=\"text-2xl font-bold text-purple-600\">ChatWave</h1>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <nav class=\"hidden md:ml-6 md:flex md:space-x-8\">\r\n");
      out.write("                        <a href=\"#features\" class=\"inline-flex items-center px-1 pt-1 text-sm font-medium text-gray-500 hover:text-gray-700\">Features</a>\r\n");
      out.write("                        <a href=\"#pricing\" class=\"inline-flex items-center px-1 pt-1 text-sm font-medium text-gray-500 hover:text-gray-700\">Pricing</a>\r\n");
      out.write("                        <a href=\"#testimonials\" class=\"inline-flex items-center px-1 pt-1 text-sm font-medium text-gray-500 hover:text-gray-700\">Testimonials</a>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex items-center\">\r\n");
      out.write("                    <a href=\"login.jsp\" class=\"inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-gray-900\">\r\n");
      out.write("                        Log in\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"signup.jsp\" class=\"ml-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500\">\r\n");
      out.write("                        Sign up\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Hero Section -->\r\n");
      out.write("    <section class=\"pt-24 pb-12 md:pt-32 md:pb-20\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"lg:grid lg:grid-cols-12 lg:gap-8\">\r\n");
      out.write("                <div class=\"sm:text-center md:max-w-2xl md:mx-auto lg:col-span-6 lg:text-left\">\r\n");
      out.write("                    <h1>\r\n");
      out.write("                        <span class=\"block text-sm font-semibold uppercase tracking-wide text-gray-500 sm:text-base lg:text-sm xl:text-base\">\r\n");
      out.write("                            Introducing\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <span class=\"mt-1 block text-4xl tracking-tight font-extrabold sm:text-5xl xl:text-6xl\">\r\n");
      out.write("                            <span class=\"block text-gray-900\">Team chat for the</span>\r\n");
      out.write("                            <span class=\"block text-purple-600\">modern workplace</span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </h1>\r\n");
      out.write("                    <p class=\"mt-3 text-base text-gray-500 sm:mt-5 sm:text-xl lg:text-lg xl:text-xl\">\r\n");
      out.write("                        ChatWave helps your team collaborate seamlessly. Share files, chat in real-time, and keep your projects moving forward with our intuitive platform.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div class=\"mt-8 sm:max-w-lg sm:mx-auto sm:text-center lg:text-left lg:mx-0\">\r\n");
      out.write("                        <div class=\"mt-5 sm:mt-8 sm:flex sm:justify-center lg:justify-start\">\r\n");
      out.write("                            <div class=\"rounded-md shadow\">\r\n");
      out.write("                                <a href=\"signup.html\" class=\"w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-purple-600 hover:bg-purple-700 md:py-4 md:text-lg md:px-10\">\r\n");
      out.write("                                    Get started\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mt-3 sm:mt-0 sm:ml-3\">\r\n");
      out.write("                                <a href=\"#features\" class=\"w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-purple-700 bg-purple-100 hover:bg-purple-200 md:py-4 md:text-lg md:px-10\">\r\n");
      out.write("                                    Learn more\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mt-12 relative sm:max-w-lg sm:mx-auto lg:mt-0 lg:max-w-none lg:mx-0 lg:col-span-6 lg:flex lg:items-center\">\r\n");
      out.write("                    <div class=\"relative mx-auto w-full rounded-lg shadow-lg lg:max-w-md\">\r\n");
      out.write("                        <img class=\"w-full\" src=\"https://images.unsplash.com/photo-1557804506-669a67965ba0?ixlib=rb-1.2.1&auto=format&fit=crop&w=1567&q=80\" alt=\"ChatWave app screenshot\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Features Section -->\r\n");
      out.write("    <section id=\"features\" class=\"py-12 bg-white\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"lg:text-center\">\r\n");
      out.write("                <h2 class=\"text-base text-purple-600 font-semibold tracking-wide uppercase\">Features</h2>\r\n");
      out.write("                <p class=\"mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl\">\r\n");
      out.write("                    Everything you need to connect\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto\">\r\n");
      out.write("                    ChatWave provides all the tools your team needs to communicate effectively.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mt-10\">\r\n");
      out.write("                <div class=\"space-y-10 md:space-y-0 md:grid md:grid-cols-2 md:gap-x-8 md:gap-y-10\">\r\n");
      out.write("                    <div class=\"relative\">\r\n");
      out.write("                        <div class=\"absolute flex items-center justify-center h-12 w-12 rounded-md bg-purple-500 text-white\">\r\n");
      out.write("                            <svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ml-16\">\r\n");
      out.write("                            <h3 class=\"text-lg leading-6 font-medium text-gray-900\">Real-time messaging</h3>\r\n");
      out.write("                            <p class=\"mt-2 text-base text-gray-500\">\r\n");
      out.write("                                Communicate with your team in real-time with instant messaging that keeps everyone in sync.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"relative\">\r\n");
      out.write("                        <div class=\"absolute flex items-center justify-center h-12 w-12 rounded-md bg-purple-500 text-white\">\r\n");
      out.write("                            <svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ml-16\">\r\n");
      out.write("                            <h3 class=\"text-lg leading-6 font-medium text-gray-900\">File sharing</h3>\r\n");
      out.write("                            <p class=\"mt-2 text-base text-gray-500\">\r\n");
      out.write("                                Share files, documents, and images with your team members instantly.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"relative\">\r\n");
      out.write("                        <div class=\"absolute flex items-center justify-center h-12 w-12 rounded-md bg-purple-500 text-white\">\r\n");
      out.write("                            <svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ml-16\">\r\n");
      out.write("                            <h3 class=\"text-lg leading-6 font-medium text-gray-900\">Team channels</h3>\r\n");
      out.write("                            <p class=\"mt-2 text-base text-gray-500\">\r\n");
      out.write("                                Organize conversations by project, team, or topic with dedicated channels.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"relative\">\r\n");
      out.write("                        <div class=\"absolute flex items-center justify-center h-12 w-12 rounded-md bg-purple-500 text-white\">\r\n");
      out.write("                            <svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("                                <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z\" />\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"ml-16\">\r\n");
      out.write("                            <h3 class=\"text-lg leading-6 font-medium text-gray-900\">Secure communications</h3>\r\n");
      out.write("                            <p class=\"mt-2 text-base text-gray-500\">\r\n");
      out.write("                                End-to-end encryption ensures your team's conversations remain private and secure.\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Pricing Section -->\r\n");
      out.write("    <section id=\"pricing\" class=\"py-12 bg-gray-50\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"lg:text-center\">\r\n");
      out.write("                <h2 class=\"text-base text-purple-600 font-semibold tracking-wide uppercase\">Pricing</h2>\r\n");
      out.write("                <p class=\"mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl\">\r\n");
      out.write("                    Plans for teams of all sizes\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto\">\r\n");
      out.write("                    Choose the perfect plan for your team's communication needs.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mt-10 space-y-12 lg:space-y-0 lg:grid lg:grid-cols-3 lg:gap-x-8\">\r\n");
      out.write("                <div class=\"relative p-8 bg-white border border-gray-200 rounded-2xl shadow-sm flex flex-col\">\r\n");
      out.write("                    <div class=\"flex-1\">\r\n");
      out.write("                        <h3 class=\"text-xl font-semibold text-gray-900\">Starter</h3>\r\n");
      out.write("                        <p class=\"mt-4 flex items-baseline text-gray-900\">\r\n");
      out.write("                            <span class=\"text-5xl font-extrabold tracking-tight\">$0</span>\r\n");
      out.write("                            <span class=\"ml-1 text-xl font-semibold\">/month</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p class=\"mt-6 text-gray-500\">Perfect for small teams just getting started.</p>\r\n");
      out.write("\r\n");
      out.write("                        <ul role=\"list\" class=\"mt-6 space-y-6\">\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">Up to 10 team members</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">5 channels</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">5GB file storage</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"signup.html\" class=\"mt-8 block w-full bg-purple-600 border border-transparent rounded-md py-2 text-sm font-semibold text-white text-center hover:bg-purple-700\">Get started</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"relative p-8 bg-white border border-gray-200 rounded-2xl shadow-sm flex flex-col\">\r\n");
      out.write("                    <div class=\"flex-1\">\r\n");
      out.write("                        <h3 class=\"text-xl font-semibold text-gray-900\">Professional</h3>\r\n");
      out.write("                        <p class=\"absolute top-0 py-1.5 px-4 bg-purple-600 rounded-full text-xs font-semibold uppercase tracking-wide text-white transform -translate-y-1/2\">Most popular</p>\r\n");
      out.write("                        <p class=\"mt-4 flex items-baseline text-gray-900\">\r\n");
      out.write("                            <span class=\"text-5xl font-extrabold tracking-tight\">$15</span>\r\n");
      out.write("                            <span class=\"ml-1 text-xl font-semibold\">/month</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p class=\"mt-6 text-gray-500\">For growing teams that need more features.</p>\r\n");
      out.write("\r\n");
      out.write("                        <ul role=\"list\" class=\"mt-6 space-y-6\">\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">Unlimited team members</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">Unlimited channels</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">50GB file storage</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">Advanced permissions</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"signup.html\" class=\"mt-8 block w-full bg-purple-600 border border-transparent rounded-md py-2 text-sm font-semibold text-white text-center hover:bg-purple-700\">Get started</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"relative p-8 bg-white border border-gray-200 rounded-2xl shadow-sm flex flex-col\">\r\n");
      out.write("                    <div class=\"flex-1\">\r\n");
      out.write("                        <h3 class=\"text-xl font-semibold text-gray-900\">Enterprise</h3>\r\n");
      out.write("                        <p class=\"mt-4 flex items-baseline text-gray-900\">\r\n");
      out.write("                            <span class=\"text-5xl font-extrabold tracking-tight\">$29</span>\r\n");
      out.write("                            <span class=\"ml-1 text-xl font-semibold\">/month</span>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p class=\"mt-6 text-gray-500\">For large organizations with advanced needs.</p>\r\n");
      out.write("\r\n");
      out.write("                        <ul role=\"list\" class=\"mt-6 space-y-6\">\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">Everything in Professional</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">Unlimited file storage</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">24/7 priority support</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"flex\">\r\n");
      out.write("                                <svg class=\"flex-shrink-0 w-6 h-6 text-green-500\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\r\n");
      out.write("                                    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 13l4 4L19 7\" />\r\n");
      out.write("                                </svg>\r\n");
      out.write("                                <span class=\"ml-3 text-gray-500\">Advanced security features</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"signup.html\" class=\"mt-8 block w-full bg-purple-600 border border-transparent rounded-md py-2 text-sm font-semibold text-white text-center hover:bg-purple-700\">Get started</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Testimonials Section -->\r\n");
      out.write("    <section id=\"testimonials\" class=\"py-12 bg-white\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"lg:text-center\">\r\n");
      out.write("                <h2 class=\"text-base text-purple-600 font-semibold tracking-wide uppercase\">Testimonials</h2>\r\n");
      out.write("                <p class=\"mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl\">\r\n");
      out.write("                    Trusted by teams worldwide\r\n");
      out.write("                </p>\r\n");
      out.write("                <p class=\"mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto\">\r\n");
      out.write("                    See what our customers have to say about ChatWave.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mt-10\">\r\n");
      out.write("                <div class=\"space-y-10 md:space-y-0 md:grid md:grid-cols-2 md:gap-x-8 md:gap-y-10\">\r\n");
      out.write("                    <div class=\"bg-gray-50 rounded-lg p-6 shadow-sm\">\r\n");
      out.write("                        <div class=\"flex items-start\">\r\n");
      out.write("                            <div class=\"flex-shrink-0\">\r\n");
      out.write("                                <img class=\"h-12 w-12 rounded-full\" src=\"https://randomuser.me/api/portraits/women/32.jpg\" alt=\"Sarah Johnson\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"ml-4\">\r\n");
      out.write("                                <h4 class=\"text-lg font-bold text-gray-900\">Sarah Johnson</h4>\r\n");
      out.write("                                <p class=\"text-sm text-gray-500\">Marketing Director, TechCorp</p>\r\n");
      out.write("                                <div class=\"mt-1 flex items-center\">\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"mt-4 text-gray-600\">\r\n");
      out.write("                            \"ChatWave has transformed how our marketing team collaborates. The interface is intuitive, and the file sharing capabilities have made our workflow so much smoother.\"\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"bg-gray-50 rounded-lg p-6 shadow-sm\">\r\n");
      out.write("                        <div class=\"flex items-start\">\r\n");
      out.write("                            <div class=\"flex-shrink-0\">\r\n");
      out.write("                                <img class=\"h-12 w-12 rounded-full\" src=\"https://randomuser.me/api/portraits/men/46.jpg\" alt=\"Michael Chen\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"ml-4\">\r\n");
      out.write("                                <h4 class=\"text-lg font-bold text-gray-900\">Michael Chen</h4>\r\n");
      out.write("                                <p class=\"text-sm text-gray-500\">Product Manager, InnovateCo</p>\r\n");
      out.write("                                <div class=\"mt-1 flex items-center\">\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    <svg class=\"h-5 w-5 text-yellow-400\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 20 20\" fill=\"currentColor\">\r\n");
      out.write("                                        <path d=\"M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"mt-4 text-gray-600\">\r\n");
      out.write("                            \"As a product manager, I need to coordinate with multiple teams. ChatWave has made it easy to keep everyone on the same page with its organized channels and seamless file sharing.\"\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- CTA Section -->\r\n");
      out.write("    <section class=\"py-12 bg-purple-600\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"text-center\">\r\n");
      out.write("                <h2 class=\"text-3xl font-extrabold text-white sm:text-4xl\">\r\n");
      out.write("                    <span class=\"block\">Ready to get started?</span>\r\n");
      out.write("                    <span class=\"block\">Sign up for ChatWave today.</span>\r\n");
      out.write("                </h2>\r\n");
      out.write("                <p class=\"mt-4 text-lg leading-6 text-purple-200\">\r\n");
      out.write("                    Join thousands of teams that use ChatWave to collaborate more effectively.\r\n");
      out.write("                </p>\r\n");
      out.write("                <div class=\"mt-8 flex justify-center\">\r\n");
      out.write("                    <div class=\"inline-flex rounded-md shadow\">\r\n");
      out.write("                        <a href=\"signup.html\" class=\"inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-purple-600 bg-white hover:bg-purple-50\">\r\n");
      out.write("                            Sign up for free\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"ml-3 inline-flex\">\r\n");
      out.write("                        <a href=\"#features\" class=\"inline-flex items-center justify-center px-5 py-3 border border-transparent text-base font-medium rounded-md text-white bg-purple-700 hover:bg-purple-800\">\r\n");
      out.write("                            Learn more\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"bg-white\">\r\n");
      out.write("        <div class=\"max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8\">\r\n");
      out.write("            <div class=\"md:flex md:items-center md:justify-between\">\r\n");
      out.write("                <div class=\"flex justify-center md:justify-start\">\r\n");
      out.write("                    <h2 class=\"text-2xl font-bold text-purple-600\">ChatWave</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mt-8 md:mt-0\">\r\n");
      out.write("                    <p class=\"text-center text-base text-gray-400\">\r\n");
      out.write("                        &copy; 2023 ChatWave, Inc. All rights reserved.\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mt-8 border-t border-gray-200 pt-8 md:flex md:items-center md:justify-between\">\r\n");
      out.write("                <div class=\"flex space-x-6 md:order-2\">\r\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-gray-500\">\r\n");
      out.write("                        <span class=\"sr-only\">Facebook</span>\r\n");
      out.write("                        <svg class=\"h-6 w-6\" fill=\"currentColor\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\r\n");
      out.write("                            <path fill-rule=\"evenodd\" d=\"M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z\" clip-rule=\"evenodd\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-gray-500\">\r\n");
      out.write("                        <span class=\"sr-only\">Instagram</span>\r\n");
      out.write("                        <svg class=\"h-6 w-6\" fill=\"currentColor\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\r\n");
      out.write("                            <path fill-rule=\"evenodd\" d=\"M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z\" clip-rule=\"evenodd\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"#\" class=\"text-gray-400 hover:text-gray-500\">\r\n");
      out.write("                        <span class=\"sr-only\">Twitter</span>\r\n");
      out.write("                        <svg class=\"h-6 w-6\" fill=\"currentColor\" viewBox=\"0 0 24 24\" aria-hidden=\"true\">\r\n");
      out.write("                            <path d=\"M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84\" />\r\n");
      out.write("                        </svg>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mt-8 md:mt-0 md:order-1\">\r\n");
      out.write("                    <nav class=\"flex space-x-6\">\r\n");
      out.write("                        <a href=\"#\" class=\"text-gray-500 hover:text-gray-900\">Privacy</a>\r\n");
      out.write("                        <a href=\"#\" class=\"text-gray-500 hover:text-gray-900\">Terms</a>\r\n");
      out.write("                        <a href=\"#\" class=\"text-gray-500 hover:text-gray-900\">Contact</a>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
